import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"
import FrontendTracerProvider from "@/app/providers/frontend-tracer-provider"

const inter = localFont({ src: "./inter-variable-font.ttf" })

export const metadata: Metadata = {
  title: "Create Nhollas App",
  description: "Generated by create-nhollas-app",
  icons: {
    icon: "/favicon.svg",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <FrontendTracerProvider>
      <html lang="en" className="bg-black">
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </html>
    </FrontendTracerProvider>
  )
}
